In [14]:
import numpy as np

a = np.arange(50)
print(a)
b = a.reshape(2,25)
print(b)
c = b.reshape(5,2,5)
print(c)
# d = b.reshape(2,5,5)
# print(d)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]]


In [4]:
import numpy as np
import tensorflow as tf
a = np.arange(24).reshape(2,3,4)
print(a[1,:])
b = np.rollaxis(a,1,0)
print(b)
print(b.shape)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
(3, 2, 4)


In [192]:
whos

Variable   Type        Data/Info
--------------------------------
a          ndarray     2x3x2: 12 elems, type `int32`, 48 bytes
b          list        n=4
c          ndarray     2x3x2: 12 elems, type `int32`, 48 bytes
d          ndarray     3x10: 30 elems, type `int32`, 120 bytes
e          ndarray     2x3x5: 30 elems, type `int32`, 120 bytes
f          list        n=2
g          ndarray     2x3x2: 12 elems, type `int32`, 48 bytes
h          NoneType    None
k          list        n=3
np         module      <module 'numpy' from 'E:\<...>ges\\numpy\\__init__.py'>


In [200]:
a=np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
b = []
# print(a)

b.append(a)
# print(b)
a = a+1
# print(b)
# print(a)
b.append(a)
print(len(b))
# print(b)
b = np.array(b)
# print(b)
b = b.reshape(-1,3,2)
b = b.tolist()
# b = np.array(b)
k = b[1]
print(b[1])

2
[[1, 2], [3, 4], [5, 6]]


In [205]:
import math
math.floor([[1]])

TypeError: must be real number, not list

In [197]:
import os
path = 'F:/tempo sim data/224Gbpers_28GBaud_DP-16QAM_1Saperb_18dB_2dBm_0.01-0.6/train_data/'
filelist = os.listdir(path)
print(filelist)
filepath = os.path.join(path,filelist[1])
print(filepath)

['224Gbpers_28GBaud_DP-16QAM_1Saperb_18dB_2dBm_0.01_No.1.mat', '224Gbpers_28GBaud_DP-16QAM_1Saperb_18dB_2dBm_0.01_No.2.mat']
F:/tempo sim data/224Gbpers_28GBaud_DP-16QAM_1Saperb_18dB_2dBm_0.01-0.6/train_data/224Gbpers_28GBaud_DP-16QAM_1Saperb_18dB_2dBm_0.01_No.2.mat


In [40]:
import numpy as np
a = np.random.randint(0,10,size=[5,5,5])
print(a)
b=1
c=3
print(a[b:c])

[[[5 3 8 9 0]
  [0 8 0 5 8]
  [2 1 0 8 2]
  [8 9 4 2 4]
  [6 9 7 9 2]]

 [[7 3 7 5 4]
  [3 4 2 0 8]
  [8 9 9 4 8]
  [1 8 6 1 4]
  [5 6 4 0 9]]

 [[6 6 8 7 2]
  [9 0 8 3 8]
  [6 2 5 0 7]
  [2 0 0 8 1]
  [5 2 8 6 6]]

 [[6 9 8 5 2]
  [2 6 0 5 0]
  [9 3 6 5 3]
  [2 7 7 0 7]
  [7 8 9 6 0]]

 [[7 0 8 6 9]
  [9 0 1 3 7]
  [3 7 0 6 9]
  [2 8 4 0 3]
  [1 4 5 5 4]]]
[[[7 3 7 5 4]
  [3 4 2 0 8]
  [8 9 9 4 8]
  [1 8 6 1 4]
  [5 6 4 0 9]]

 [[6 6 8 7 2]
  [9 0 8 3 8]
  [6 2 5 0 7]
  [2 0 0 8 1]
  [5 2 8 6 6]]]
